// Generated by CoffeeScript 1.9.3
var transform_barycentric;

transform_barycentric = function(data, transformation) {
  var genecoords;
  genecoords = math.transpose(math.multiply(transformation, data));
  return genecoords;
};
