// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// backgroundModel
List backgroundModel(NumericVector angles, int nsamples, int samplesize, int nangles, double bw);
RcppExport SEXP triwise_backgroundModel(SEXP anglesSEXP, SEXP nsamplesSEXP, SEXP samplesizeSEXP, SEXP nanglesSEXP, SEXP bwSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< NumericVector >::type angles(anglesSEXP);
    Rcpp::traits::input_parameter< int >::type nsamples(nsamplesSEXP);
    Rcpp::traits::input_parameter< int >::type samplesize(samplesizeSEXP);
    Rcpp::traits::input_parameter< int >::type nangles(nanglesSEXP);
    Rcpp::traits::input_parameter< double >::type bw(bwSEXP);
    __result = Rcpp::wrap(backgroundModel(angles, nsamples, samplesize, nangles, bw));
    return __result;
END_RCPP
}
