// This file was automatically generated by 'Kmisc::registerFunctions()'

#include <R.h>
#include <Rinternals.h>

#include <R_ext/Rdynload.h>

SEXP triwise_backgroundModel2(SEXP anglesSEXP, SEXP RSEXP, SEXP nsamplesSEXP, SEXP samplesizeSEXP, SEXP anglesoiSEXP, SEXP bwSEXP);
//' @title backgroundModel2//' @description Generates a triwise background model, containing weights, z-values and angle p-values for a set of uniformly distributed reference angles//' @param angles//' @param nsamples//' @param samplesize//' @param nangles//' @param bw// [[Rcpp::depends("RcppArmadillo")]]// [[Rcpp::export]]List backgroundModel2(NumericVector angles, NumericVector R, int nsamples, int samplesize, NumericVector anglesoi, double bw);

R_CallMethodDef callMethods[]  = {
  {"triwise_backgroundModel2", (DL_FUNC) &triwise_backgroundModel2, 6},
  {NULL, NULL, 0}
};

void R_init_triwise(DllInfo *info) {
  R_registerRoutines(info, NULL, callMethods, NULL, NULL);
  R_useDynamicSymbols(info, FALSE);
}

