# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @export
backgroundModel <- function(angles, nsamples, samplesize, nangles, bw) {
    .Call('triwise_backgroundModel', PACKAGE = 'triwise', angles, nsamples, samplesize, nangles, bw)
}

